# Generated by Django 3.2.25 on 2024-10-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Job!', max_length=60)),
                ('description', models.TextField(default='', max_length=1000)),
                ('job_Type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Part Time', max_length=15)),
                ('vacancy', models.IntegerField(default='1')),
                ('salary', models.IntegerField(default='0')),
                ('published_on', models.DateTimeField(auto_now=True)),
                ('qualification', models.IntegerField(default='0')),
                ('Date_Line', models.DateTimeField()),
            ],
        ),
    ]
