# Generated by Django 3.2.25 on 2024-11-03 19:41

import Jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='image',
            field=models.ImageField(default='', upload_to=Jobs.models.pickImage),
            preserve_default=False,
        ),
    ]
