# Generated by Django 3.2.25 on 2024-11-03 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_auto_20241103_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Jobs.category'),
            preserve_default=False,
        ),
    ]
