# Generated by Django 3.2.25 on 2024-11-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_jobs_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('website', models.URLField()),
                ('cv', models.FileField(max_length=1000, upload_to='apply/')),
                ('coverletter', models.TextField(default='', max_length=500)),
                ('applied_at', models.DateTimeField(auto_now=True)),
                ('is_replayed', models.BooleanField(default=False)),
                ('apply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobs', verbose_name='Apply to')),
            ],
        ),
    ]
